- .github/workflows/ci.yml
- .husky/pre-commit
- cspell.json
- package-lock.json
- packages/json-api/.eslintrc.json
- packages/json-api/README.md
- packages/json-api/examples/toJsonApiQuery.ts
- packages/json-api/examples/toSearchParams.ts
- packages/json-api/jest.config.ts
- packages/json-api/package.json
- packages/json-api/project.json
- packages/json-api/src/index.ts
- packages/json-api/src/lib/toJsonApiQuery.spec.ts
- packages/json-api/src/lib/toJsonApiQuery.ts
- packages/json-api/src/lib/toSearchParams.spec.ts
- packages/json-api/src/lib/toSearchParams.ts
- packages/json-api/src/lib/types.ts
- packages/json-api/tsconfig.json
- packages/json-api/tsconfig.lib.json
- packages/json-api/tsconfig.lint.json
- packages/json-api/tsconfig.spec.json
- packages/json-api/typedoc.json
- tsconfig.base.json
Summary
===
Add `json-api` query helpers inspired by https://github.com/scoutforpets/bookshelf-jsonapi-params and https://github.com/kideh88/node-jsonapi-query-parser. See the README for example usage.
> feat: json-api query helpers

- packages/json-api/README.md
- packages/json-api/examples/toJsonApiQuery.ts
- packages/json-api/examples/toSearchParams.ts
- packages/json-api/src/lib/toJsonApiQuery.spec.ts
- packages/json-api/src/lib/toJsonApiQuery.ts
- packages/json-api/src/lib/toSearchParams.spec.ts
- packages/json-api/src/lib/toSearchParams.ts
- packages/json-api/src/lib/types.ts
Changes
---
- Create `ClientJsonApiQuery` and `ServerJsonApiQuery` types. The former provide better type safety while the latter remain `string`.
- Client-side, support `boolean`, `Date`, and `number` types in addition to `string`.
- Add `deepEqual` asserts to the examples to quickly verify correctness.
- More complete tests
- Better 🐶 names
> feat: allow clients to pass boolean, Date, and number values

- packages/json-api/src/lib/toSearchParams.ts
Summary
===
When using `json-api` in client side, we get the following warning
Node.js already supports using `URLSearchParams` under the `globalThis`. Hence we don't need to import them explicitly.
Changes
---
- remove `node:url` import to be compatible with client side
---
> fix: makes URLSearchParams global and remove node import

- .coderabbit.yaml
- package-lock.json
- packages/json-api-nestjs/README.md
- packages/json-api-nestjs/examples/query.ts
- packages/json-api-nestjs/examples/type-checks/createCursorPagination.ts
- packages/json-api-nestjs/examples/type-checks/createFields.ts
- packages/json-api-nestjs/examples/type-checks/createFilter.ts
- packages/json-api-nestjs/examples/type-checks/createInclude.ts
- packages/json-api-nestjs/examples/type-checks/createSort.ts
- packages/json-api-nestjs/package.json
- packages/json-api-nestjs/src/index.ts
- packages/json-api-nestjs/src/lib/query/createInclude.spec.ts
- packages/json-api-nestjs/src/lib/query/createInclude.ts
- packages/json-api-nestjs/src/lib/query/createSort.ts
Summary
===
- **New Features**
- Introduced a `createInclude` function for validating JSON:API include parameters.
- Enhanced query handling with a consolidated `query` constant that includes pagination, fields, filters, sorting, and related resource inclusion.
- **Bug Fixes**
- Improved error handling and validation feedback for sorting and include parameters.
- **Documentation**
- Updated the README to include examples of using query helpers for better clarity.
- **Tests**
- Added a comprehensive suite of unit tests for the `createInclude` function to ensure robust validation.
- **Chores**
- Updated configuration files and package scripts for improved functionality.
> feat: Zod schema for JSON:API include query parameters

- package-lock.json
- packages/util-typescript/README.md
- packages/util-typescript/examples/serviceError.ts
- packages/util-typescript/examples/serviceResult.ts
- packages/util-typescript/src/lib/errors/serviceError.spec.ts
- packages/util-typescript/src/lib/errors/serviceError.ts
Changes
---
- Allow ServiceError creation with just a message like a normal error, `new ServiceError("boom")`
- Make `code` optional
- Don't allow custom `title`s per the JSON:API spec
- Rename `detail` to `message` and only call it `detail` when converting to JSON:API error
> fix: make ServiceError easier to use

- packages/util-ts/src/lib/functional/option.spec.ts
- packages/util-ts/src/lib/functional/option.ts
Summary
===
Adds `fromNullable` to Option 
Changes
---
-
---
> feat: add fromNullable to Option

- packages/eslint-config/src/index.js
- packages/eslint-config/src/index.spec.ts
While `continue` can be misused, especially with nested loops and labels, it can be useful for preventing code nesting and the existence of the rule caused us to lose time debating its validity
See full slack discussion about it [here](https://clipboardhealth.slack.com/archives/C03GV3J181X/p1736877828918619)
> feat: disable no-continue eslint rule

- package-lock.json
- packages/config/package.json
- packages/contract-core/package.json
- packages/json-api-nestjs/package.json
- packages/testing-core/package.json
- packages/util-ts/package.json
Summary
===
Move Zod to `peerDependencies` to avoid version conflicts.
> fix: move zod to peer dep

- packages/rules-engine/README.md
- packages/rules-engine/examples/rules.ts
- packages/rules-engine/src/lib/runners/allIf.spec.ts
- packages/rules-engine/src/lib/runners/allIf.ts
- packages/rules-engine/src/lib/runners/index.ts
Summary
===
Changes
---
- We have been using this new runner for different scenarios in curated shifts when we want to reuse existing rules for a new vertical or specific flow. (examples [here](https://github.com/ClipboardHealth/open-shifts/blob/main/curated-shifts/src/modules/pricing/rules/fixed-rates-workplaces.ts#L16), [here](https://github.com/ClipboardHealth/open-shifts/blob/main/curated-shifts/src/modules/pricing/rules/workplace-types/education.ts#L20))
- This runner applies all the rules that match the runIf criteria **only** when the first argument (a function) returns true.
- This overrides the previous allIf, which we never exported and used.
---
> chore: add the allIf runner to the rules engine

- packages/util-ts/src/lib/errors/serviceError.spec.ts
- packages/util-ts/src/lib/errors/serviceError.ts
- packages/util-ts/src/lib/functional/serviceResult.spec.ts
Summary
===
This started getting called by our HttpExceptionFilter in `cbh-core` in [this commit](https://github.com/ClipboardHealth/cbh-core/commit/894547763fd9d80c0d5bdc7584b802798ab8ebf7), which changed the status code from 400 to 422. This PR reverts that breaking change.
This is another breaking change, but the since the vast majority of services haven't updated yet, it's easier to revert.
> fix!: return 400 instead of 422 for backward compat

- package-lock.json
- packages/eslint-config/package.json
Summary
===
Changes
---
- Fix the version of eslint-config-xo package to `^0.45.0`, as just `^0.45` updates the minor version to a version that requires eslint v9 as a peer dependency
---
> fix: correct eslint-config-xo version

- packages/eslint-config/src/index.js
- packages/eslint-config/src/index.spec.ts
- packages/json-api-nestjs/src/lib/internal/queryFilterPreprocessor.ts
- packages/json-api/src/lib/query/stringifyQuery.spec.ts
- packages/testing-core/src/lib/expectToBeDefined.spec.ts
- packages/util-ts/src/lib/deepFreeze.spec.ts
- packages/util-ts/src/lib/errors/isError.spec.ts
- packages/util-ts/src/lib/errors/toError.spec.ts
- packages/util-ts/src/lib/errors/toErrorMessage.spec.ts
- packages/util-ts/src/lib/functional/option.spec.ts
- packages/util-ts/src/lib/nullish/isDefined.spec.ts
- packages/util-ts/src/lib/nullish/isNil.spec.ts
- packages/util-ts/src/lib/nullish/nullToUndefined.spec.ts
- packages/util-ts/src/lib/strings/isString.spec.ts
- packages/util-ts/src/lib/strings/stringify.spec.ts
Summary
===
React, MongoDB, and Prisma use `null` and there's [lots of argument](https://github.com/sindresorhus/meta/discussions/7) over the `unicorn/no-null` rule; disable it. Also, make `no-await-in-loop` a warn so LLMs don't write worse code to get around it.
> fix: disable unicorn/no-null, make no-await-in-loop a warn

- packages/util-ts/src/lib/errors/serviceError.spec.ts
- packages/util-ts/src/lib/errors/serviceError.ts
Summary
===
https://linear.app/clipboardhealth/issue/AMA-118/implement-fromjsonapi-into-serviceerror-in-clipboard-healthutil-ts
Changes
---
- Added fromJsonApi method to ServiceError class to convert JSON:API error objects into ServiceError instances.
- Implemented tests for various scenarios including full, minimal, and multiple JSON:API errors, as well as handling different source types.
- Ensured that conversion to and from JSON:API format maintains data integrity without loss.
---
> feat(AMA-118): implement fromJsonApi method in ServiceError for JSONAPI error conversion

- packages/eslint-config/src/index.js
- packages/eslint-config/src/index.spec.ts
Summary
===
TypeScript articulated its current governing principle: TC39, the JavaScript governing body, defines the runtime, while TypeScript innovates solely in the type space. Enums predate this principle. From the [TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/enums.html#const-enum-pitfalls):
> Enums are one of the few features TypeScript has which is not a type-level extension of JavaScript.
The same page [discuses enum pitfalls](https://www.typescriptlang.org/docs/handbook/enums.html#const-enum-pitfalls). Using these non-type-level extensions aren't supported by type strippers like the one built into NodeJS. Effective TypeScript recommends against them (I've [copied the relevant book section](https://www.notion.so/Effective-TypeScript-Avoid-Enums-1cb8643321f480cda …
> feat!: ban enums

- packages/eslint-config/src/index.js
- packages/eslint-config/src/index.spec.ts
Summary
===
There aren't many benefits of this rule, in some cases it makes code more difficult to maintain.
> feat: disable `sonarjs/no-duplicate-string` for all files

- package-lock.json
- packages/config/package.json
- packages/example-nestjs/jest.config.ts
- packages/example-nestjs/package.json
- packages/json-api-nestjs/package.json
Summary
===
This is preventing usage of versions like 20.5.0
Changes
---
- Switch from `^` to `>=`
---
> fix: allow nx versions >= 20.4.6

- packages/eslint-config/src/index.js
- packages/eslint-config/src/index.spec.ts
Summary
===
As I wrote about in https://www.notion.so/date-fns-tz-is-bad-let-s-block-it-1ed8643321f48095a67afe8509b92c82, `date-fns-tz` is problematic and we should block it from being used moving forward.
This PR adds an eslint rule whch blocks the use of date-fns-tz
---
Added an ESLint rule to block importing the date-fns-tz package and suggest alternatives.
> feat: add eslint rule which blocks the use of date-fns-tz

- .eslintignore
- package-lock.json
- packages/eslint-config/package.json
- packages/eslint-config/src/index.js
- packages/eslint-config/src/index.spec.ts
- packages/example-nestjs/package.json
Changes
---
- This is a follow-up to #131 where a new `eslint-plugin` package was introduced containing definitions for custom ESLint rules.
- This PR incorporates that plugin into the config exported by `@clipboard-health/eslint-config` so that using the config results in the rules in the plugin being automatically enabled. Consuming project do not need to directly install the `eslint-plugin` package.
- The PR also skips running the linter on the linter config itself since the linter errors are not very useful and cause unavoidable typing issues to appear on a .js file.
> feat: Include rules from `eslint-plugin` in `eslint-config`

- package-lock.json
- packages/example-nestjs/package.json
- packages/util-ts/src/lib/errors/serviceError.spec.ts
- packages/util-ts/src/lib/errors/serviceError.ts
Summary
===
Ticket: https://linear.app/clipboardhealth/issue/TF-2180/core-remove-serviceerror-whitelist-to-enable-custom-error-codes
`ServiceError` exposed a hard-coded union (`ERROR_CODES`) that limited us to nine generic strings. Because callers couldn’t introduce new codes, multiple places work around by parsing the error message to infer behaviour. 
This PR removes that blocker and aligns our error shape with the JSON:API spec.
More details: https://www.notion.so/HLD-Error-Handling-with-JSON-API-Error-Objects-1f38643321f4801daf4dd24ce62b0ed1
Changes
---
- `ErrorCode` widened , now `built-ins | (string & {})`
- `ServiceIssue` extended
- `code`: now accepts custom strings
- `title?`:  optional short summary (errors.title)
- `status?`: optional HTTP status (errors.status)
> feat(TF-2180): custom error code in ServiceError

- packages/notifications/src/lib/notificationClient.spec.ts
- packages/notifications/src/lib/notificationClient.ts
- packages/notifications/src/lib/types.ts
Summary
===
Call `signUserToken` from `NotificationClient` and follow the pattern we use for the other Knock API calls. Calling this from `clipboard-health` allows us to drop the `@knocklabs/node` direct dependency so we're only pulling Knock into `core-utils` and don't have to worry about version mismatches.
> feat: add NotificationClient.signUserToken
